### ISSUE TITLE
Configure DNS with Terraform

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-org-configurations#163]
Our DNS is handled by Netlify.

API: https://open-api.netlify.com/#tag/dnsZone

There is a Terraform provider, but it doesn't support the DNS API: https://registry.terraform.io/search/providers?q=netlify

**Comment by zimbatm** [comment]
I contacted DNSMadeEasy to see if they have an Open-Source plan.

**Comment by zimbatm** [comment]
Still haven't heard back from DME

**Comment by aaronjanse** [comment]
It looks like [AegirHealth's provider](https://registry.terraform.io/providers/AegirHealth/netlify/latest) possibly [supports the DNS API](https://github.com/AegirHealth/terraform-provider-netlify/commit/c7d33724c2943d42a503f34f750af492445bf5d6)? I'm likely misunderstanding, since I don't know much about Terraform

**Comment by zimbatm** [comment]
Thanks, I missed that because their doc is not listing the new resources.
