### ISSUE TITLE
Switch the nixos.org nameservers

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-org-configurations#74]
After #68, this is the new list of name servers to be switch to at united domains:
```
ns-1455.awsdns-53.org
ns-1875.awsdns-42.co.uk
ns-483.awsdns-60.com
ns-998.awsdns-60.net
```

There is the DNS server config and there should be a separate place where just the nameservers can be switched away from the registrar-hosted DNS.

**Comment by zimbatm** [comment]
It should take ~24h for the DNS to switch to the Route53-provided ones

**Comment by grahamc** [comment]
@zimbatm I propose we set the TTLs quite low, then do the switch, then bring them back up to normal levels. Then if there is a major mistake of some sort which we can't find now, it won't take a long time to repair them.

**Comment by zimbatm** [comment]
@grahamc I don't think that this TTL is configurable. It's not served by the registrar DNS, but by the "org" TLD.

**Comment by grahamc** [comment]
Right. I mean record TTLs.

**Comment by grahamc** [comment]
The switch happened at 19:25Z, and cache.nixos.org and releases.nixos.org had some bad records -- not sure what. @edolstra repaired them in https://github.com/NixOS/nixos-org-configurations/compare/8d7b0b693424...45b25e60056e. Because of the 1hr TTL on both of those records, there will be a downtime for some users for the next or so while the TTL is replaced. Something to learn from and to handle differently next time :)

**Comment by grahamc** [comment]
More information: https://discourse.nixos.org/t/the-cache-is-down-with-workaround/1720/3
